spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect